background_image:
  type: upload
  default: "assets/balls_background.png"
  description: background image for site

banner_image:
  type: upload
  default: "assets/simple_banner.png"
  description: banner for site

rotate_banner:
  default: "https://i.imgur.com/ES1JXM3.png|https://i.imgur.com/NefzwFH.png"
  type: list
